language: php
php:
  - 7.3
  - 7.4
  - 8.0
  - 8.1

env:
  - dependencies=

script: ./vendor/bin/phpunit --coverage-text

matrix:
  include:
    - php: 7.3
      env: dependencies=lowest
    - php: 7.3
      env: dependencies=highest
    - php: 7.4
      env: dependencies=lowest
    - php: 7.4
      env: dependencies=highest
    - php: 8.0
      env: dependencies=lowest
    - php: 8.0
      env: dependencies=highest
    - php: 8.1
      env: dependencies=lowest
    - php: 8.1
      env: dependencies=highest

before_script:
    - if [ -z "$dependencies" ]; then composer install -n; fi;
    - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;
    - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
